spring:
  application:
    name: springboot-jwt

server:
  port: 8084

eureka:
  instance:
    instance-id: localhost:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
